# Generated by Django 5.2 on 2025-04-10 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dieta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcion', models.FloatField()),
                ('unidad', models.CharField(max_length=50)),
                ('calorias', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('grasas', models.FloatField()),
                ('fibra', models.FloatField(blank=True, null=True)),
                ('azucares', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlimentoMomentoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimento.alimento')),
                ('momento_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dieta.momentodia')),
            ],
        ),
        migrations.AddField(
            model_name='alimento',
            name='momento_dia',
            field=models.ManyToManyField(blank=True, related_name='alimentos', through='alimento.AlimentoMomentoDia', to='dieta.momentodia'),
        ),
    ]
