# Generated by Django 5.2 on 2025-04-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo_ejercicio', models.CharField(choices=[('fuerza', 'Fuerza'), ('cardio', 'Cardio'), ('flexibilidad', 'Flexibilidad')], max_length=50)),
                ('url_video', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioDiaRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('peso', models.FloatField()),
                ('orden', models.IntegerField()),
                ('dia_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutina.diarutina')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejercicio.ejercicio')),
            ],
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='dia_rutina',
            field=models.ManyToManyField(blank=True, related_name='ejercicios', through='ejercicio.EjercicioDiaRutina', to='rutina.diarutina'),
        ),
    ]
